export const ACTION_TYPE = {
  SET_PENDING: 'SET_PENDING',
  SET_ERROR: 'SET_ERROR',
  SET_SESSION: 'SET_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',

  SET_GRAPHICS: 'SET_GRAPHICS',
  ADD_GRAPHICS_ITEM: 'ADD_GRAPHICS_ITEM',
  REMOVE_GRAPHICS_ITEM: 'REMOVE_GRAPHICS_ITEM',

  SET_DOC_DATA: 'SET_DOC_DATA',
  SET_DOC_CHANGED: 'SET_DOC_CHANGED',
  SET_DOC_PUBLIC_STATUS: 'SET_DOC_PUBLIC_STATUS',
  RESET_DOC_DATA: 'RESET_DOC_DATA',
}
