export const ACTION_TYPE = {
  SET_SESSION: 'SET_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',

  SET_DOCS_LIST: 'SET_DOCS_LIST',

  SET_DOC_DATA: 'SET_DOC_DATA',
  SET_DOC_CHANGED: 'SET_DOC_CHANGED',
  SET_DOC_PUBLIC_STATUS: 'SET_DOC_PUBLIC_STATUS',
  RESET_DOC_DATA: 'RESET_DOC_DATA',
}
